### ISSUE TITLE
workers.error.log & workers.access.log not being created/written

### ISSUE THREAD

**Issue by jeffv** [LearnBoost/cluster#177] opened 2011-12-19 19:01 UTC
It appears that the event bind is failing circa /plugins/logger.js:135 

I can confirm that the 'worker' event does indeed happen, and that it is bindable.

It appears that the bind is happening long after the 'worker' event has already been emitted, resulting in the function never being called.

This was tested on node v0.4.7, v0.4.12 and cluster v0.7.6 and v0.7.7. 
This also can be shown using /examples/logger.js.

**Comment by jeffv** [comment] 2011-12-19 20:49
This appears to have been introduced in commit a3fb1eca49462125f2b36ada3bbe15639170d5e7 in v0.7.0

My feeling is that the callback for creating the directory is delaying 'worker' event bind and causing the issue. We have a race condition between the server starting workers and the directory being created.

**Comment by telendt** [comment] 2011-12-20 05:21
IMHO it's duplicate of #169.

**Comment by jeffv** [comment] 2011-12-20 15:52
Ah yes. It is. You are correct. Going to close this issue in favor of #169.

**Closed as completed** 2011-12-20 15:53 UTC
