### ISSUE TITLE
Spiky EINVAL

### ISSUE THREAD

**Issue by dvv** [LearnBoost/cluster#47] opened 2011-03-01 08:26 UTC
The simplest server `test.js`:

```
var cluster, http, server;
cluster = require('cluster');
http = require('http');
server = http.createServer(function(req, res) {
  var body;
  console.log('%s %s', req.method, req.url);
  body = 'Hello World';
  res.writeHead(200, {
    'Content-Length': body.length
  });
  return res.end(body);
});
cluster(server).set('workers',4).use(cluster.debug()).use(cluster.reload(['test.js'])).use(cluster.stats()).use(cluster.repl(30000)).listen(3000);
```

Below is typical debug output when starting workers. What can be the reason?

  info [90m- master started[0m
  info [90m- worker 0 spawned[0m
  info [90m- worker 1 spawned[0m
  info [90m- worker 2 spawned[0m
  info [90m- worker 3 spawned[0m
  info [90m- worker 0 connected[0m
  info [90m- worker 3 connected[0m
Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:878:24)
  [31merror[0m [90m- worker 0 uncaught exception EINVAL, Invalid argument[0m
Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:878:24)
  [31merror[0m [90m- worker 3 uncaught exception EINVAL, Invalid argument[0m
  [33mwarning[0m [90m- worker 0 died[0m
  info [90m- worker 0 spawned[0m
  [33mwarning[0m [90m- worker 3 died[0m
  info [90m- worker 3 spawned[0m
  info [90m- worker 1 connected[0m
  info [90m- worker 2 connected[0m
  info [90m- listening for connections[0m
Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:878:24)
  [31merror[0m [90m- worker 2 uncaught exception EINVAL, Invalid argument[0m
Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:878:24)
  [31merror[0m [90m- worker 1 uncaught exception EINVAL, Invalid argument[0m
  [33mwarning[0m [90m- worker 2 died[0m
  info [90m- worker 2 spawned[0m
  [33mwarning[0m [90m- worker 1 died[0m
  info [90m- worker 1 spawned[0m
  info [90m- worker 3 connected[0m
  info [90m- worker 0 connected[0m
  info [90m- worker 1 connected[0m
  info [90m- worker 2 connected[0m
  info [90m- shutting down[0m
  [33mwarning[0m [90m- kill(SIGKILL)[0m
  info [90m- shutdown complete[0m
  [33mwarning[0m [90m- worker 3 died[0m
  [90mdebug - exit[0m

**Comment by dvv** [comment] 2011-03-01 16:55
That is when colorful output is not so good ;) Lemme recatch

**Comment by dvv** [comment] 2011-03-01 17:06
```
  info master started
  info worker 0 spawned
  info worker 1 spawned
  info worker 0 connected
Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:878:24)
  error worker 0 uncaught exception EINVAL, Invalid argument
  warning worker 0 died
  info worker 0 spawned
  info worker 1 connected
  info listening for connections
  info worker 0 connected
  info shutting down
  warning kill(SIGKILL)
  warning worker 0 died
  warninf worker 1 died
  info shutdown complete
  debug - exit
```

**Comment by TheDeveloper** [comment] 2011-03-08 15:54
I am also experiencing this issue. It seems that when the workers are spawned, one of them dies initially but then survives when it respawns and everything continues to operate normally. It also intermittently works without errors, but usually, there is an EINVAL, Invalid Argument error for at least one of the workers, causing it to respawn.

I'm on x64 Ubuntu 9.04 LTS with 2 cores using node v0.4.2 and cluster 0.3.3

**Comment by tj** [comment] 2011-03-08 17:30
almost makes me think that "listening" has improperly been emitted on Ubuntu, although I am not sure if this would be node, libev etc. I bet if you do a setTimeout() delaying the accept() calls it would work, if so I think this might be a node bug

**Comment by dvv** [comment] 2011-03-08 18:24
which line to try to wrap by `setTimeout()`?

**Comment by weepy** [comment] 2011-03-12 16:42
any ideas on this one ?

**Comment by dvv** [comment] 2011-03-12 16:54
Suspended usage so far. Though tend to treat the bug as not hard one -- eventually, all required workers do get started :)

**Comment by bkw** [comment] 2011-03-15 18:09
+1

Linux 2.6.31-302-ec2 #7-Ubuntu SMP Tue Oct 13 19:55:22 UTC 2009 x86_64 GNU/Linux

Current node from github (4a9f2de956)

```
Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:903:24)
```

**Comment by perezd** [comment] 2011-03-17 22:05
experiencing same issue here (Ubuntu LTS, 23bit, 1 core.)

**Comment by tonymilne** [comment] 2011-03-21 00:40
Having the same problems on Ubuntu 10.04 LTS (lucid) using node 0.4.2 and cluster 0.4.2 - any help would be appreciated.

**Comment by gaspo** [comment] 2011-03-28 09:22
the same problem with node 0.4.4, cluster 0.5.2
Linux 2.6.26-2-amd64 #1 SMP x86_64 GNU/Linux

Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:905:24)

**Comment by frank06** [comment] 2011-03-31 21:34
Same problem on Ubuntu 10.04.1

**Comment by christophsturm** [comment] 2011-04-05 18:34
it seems the problem is that the file descriptor is not valid, this is the line in net.js that triggers the exception:
        var peerInfo = accept(self.fd);

**Comment by dvv** [comment] 2011-04-05 18:40
Sure. This means `accept` is called before `fd` has arrived to worker from IPC connection.

**Comment by christophsturm** [comment] 2011-04-06 11:04
this is not in any way related to ubuntu.the  testsuite also fails in arch linux.

**Comment by tj** [comment] 2011-04-06 16:29
good to know, just coincidence I guess

**Comment by ybogdanov** [comment] 2011-04-08 13:28
same problem on:

Linux dev2 2.6.18-194.3.1.el5.028stab069.6xen #1 SMP Wed May 26 18:35:38 MSD 2010 x86_64 x86_64 x86_64 GNU/Linux

cluster v0.5.5

**Comment by bkw** [comment] 2011-04-21 08:47
So it's not limited to ubuntu after all.

**Comment by 3rd-Eden** [comment] 2011-04-21 12:27
Same issue here on debian 5.0

**Comment by tj** [comment] 2011-04-21 15:44
wish I could reproduce this at least once, might have to fire up a VM, _gah_

**Comment by frank06** [comment] 2011-04-21 16:03
it's pretty easy to get those environments running with vagrant

**Comment by tj** [comment] 2011-04-21 16:15
yeah i know im just lazy :D

**Comment by mnutt** [comment] 2011-04-22 05:25
@dvv in lib/worker.js, around line 87, replacing the `self.stdin.on('fd', ...)` line with this made the problem go away for me:

```
var self = this;
self.stdin.on('fd', function(fd) {
  setTimeout(function() {
    self.server.listenFD(fd);
  }, 1000);
});
```

So yeah, @visionmedia, your assessment sounds right.

**Comment by dvv** [comment] 2011-04-22 06:13
Sure. Wonder whether `nextTick()` will do, or really some timeout must be taken?

**Comment by tj** [comment] 2011-04-22 16:50
@mnutt hmm interesting, I took a look at net.js and saw this (from listenFD): the emit() is immediate, so it's obviously expecting the syscalls to have occurred already, but since I spawn the workers before "listening" this makes perfect sense now, although kinda strange that it's fine on osx

```
    Server.prototype._startWatcher = function() {
      this.watcher.set(this.fd, true, false);
      this.watcher.start();
      this.emit('listening');
    };
```

we could try just spawning the workers _after_ listening, should still be fine

**Comment by lackac** [comment] 2011-04-24 12:01
We experienced the same issue this weekend on our staging server. Additionally, the cluster was being monitored by god which caused a never-ending respawn cycle. The circumstances in which this issue occurred is not clear to me though.

**Comment by tj** [comment] 2011-04-24 15:54
@lackac yeah we need a better way to detect this, currently I have a threshold on boot of 60 seconds (in NODE_ENV=production), within which cluster will consider it a cyclic restart since it should not be restarting that soon, and will delay the restart for another 60 seconds to at least provide some sort of control instead of recursively spawning as fast as possible

that being said I made some tweeks to cluster's internals that _should_ fix this EINVAL problem so the next release might help

**Comment by rgabo** [comment] 2011-04-26 14:21
+1 for next release to fix this

**Comment by tj** [comment] 2011-04-26 15:29
releasing riiiight now

**Comment by lackac** [comment] 2011-05-01 20:57
@visionmedia we upgraded on our server to 0.6.1 after you released it and haven't seen this issue come up since. Thanks for the fix.

**Comment by tj** [comment] 2011-05-01 20:59
@lackac awesome sounds good, I will close this for now

**Closed as completed by tj** 2011-05-01 20:59 UTC

**Comment by diversario** [comment] 2011-07-18 21:24
I started using cluster.exception and mailbox is flooded with EINVALs. It wasn't happening before today, I was on 0.6.3. Started for seemingly no reason. I upgraded to 0.6.5 and still getting exceptions.

I'm on node 0.4.9, Ubuntu 11.04.

The error is:

```
Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:916:24)
```

**Comment by tj** [comment] 2011-07-18 22:08
damn! I found some more bugs so I'm releasing another patch-level soon

**Comment by diversario** [comment] 2011-07-19 15:14
Updated to 0.6.8, so far no emails from exception, I'm cautiously optimistic :) Gonna report back by the end of the day or if I get those emails before that.

**Comment by tj** [comment] 2011-07-19 15:25
haha ok great, sounds good

**Comment by diversario** [comment] 2011-07-20 10:20
Looks like EINVAL issue is solved. Or at least something else changed and it doesn't trigger, but I didn't really do anything. So, thanks! :)

**Comment by tj** [comment] 2011-07-20 13:57
interesting, that's good though :D
