### ISSUE TITLE
EINVAL Invalid Argument Error

### ISSUE THREAD

**Issue by scott2449** [LearnBoost/cluster#52] opened 2011-03-04 16:43 UTC
So on Ubuntu 10.10 and 10.04, both w/ real server installs and virtual box installs I see the following:

```
scott@cipher:~/sampleServer$ npm ls installed
npm info it worked if it ends with ok
npm info using npm@0.3.14
npm info using node@v0.4.2
cluster@0.3.2       installed   extensible multi-core server manager     server spark fugue tcp     workers
cluster@0.3.3       active installed   extensible multi-core server manager     server spark fugue tcp workers
connect@0.5.10      active installed   High performance middleware framework     framework web middleware connect rack
connect@1.0.3       installed   High performance middleware framework     framework web middleware connect rack
express@1.0.8       active installed   Sinatra inspired web development framework     framework sinatra web rest restful
express@2.0.0beta   installed   Sinatra inspired web development framework     framework sinatra web rest restful
log@1.1.1           active installed   Tiny logger with streaming reader     log logger
mime@1.2.1          active installed   A comprehensive library for mime-type mapping     util mime
npm@0.3.12          installed   A package manager for node     package manager modules install package.json
npm@0.3.14          active installed   A package manager for node     package manager modules install package.json
qs@0.0.6            active installed   querystring parser
npm ok
scott@cipher:~/sampleServer$ node server.js
info - master started
info - worker 0 spawned
info - worker 1 spawned
info - worker 0 connected
info - worker 1 connected
info - listening for connections
Error: EINVAL, Invalid argument
at IOWatcher.callback (net.js:878:24)
error - worker 0 uncaught exception EINVAL, Invalid argument
warning - worker 0 died
info - worker 0 spawned
info - worker 0 connected
^C  info - shutting down
warning - kill(SIGKILL)
info - shutdown complete
debug - exit
```

I have tried all different versions of libraries and all the test cases. Same results... any ideas?

**Comment by tj** [comment] 2011-03-04 17:11
hmm that is the accept(self.fd) call in node failing (net.js:878), but if listen() is fine that should be ok. what about with the latest version + one worker?

**Comment by scott2449** [comment] 2011-03-04 20:00
One worker has always been been fine. Even when spawning multiples workers one usually lives. I've tried on 2 and 4 cpu machines. I have tried with node 0.4, 0.4.1, 0.4.2 as well as cluster 0.3.2 and 0.3.3 all with the same unfortunate result =( I'll be really excited to get this working.

**Comment by tj** [comment] 2011-03-04 20:32
interesting.. my co-worker Aaron is running ubuntu and has this _exact_ issue. almost seems like a listen() bug in node on linux, maybe prematurely emitting "listening", not positive, tough for me to debug at the moment

**Comment by tj** [comment] 2011-03-08 18:54
duplicate of #47, closing

**Closed as completed by tj** 2011-03-08 18:54 UTC
